# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MB/ip/MB_microblaze_0_6/MB_microblaze_0_6.xci
# IP: The module: 'MB_microblaze_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_microblaze_0_6/MB_microblaze_0_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_microblaze_0_6'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_microblaze_0_6/MB_microblaze_0_6_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_microblaze_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_microblaze_0_6/MB_microblaze_0_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_microblaze_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MB/ip/MB_microblaze_0_6/MB_microblaze_0_6.xci
# IP: The module: 'MB_microblaze_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_microblaze_0_6/MB_microblaze_0_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_microblaze_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_microblaze_0_6/MB_microblaze_0_6_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_microblaze_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_microblaze_0_6/MB_microblaze_0_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_microblaze_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
