# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrs.xdc

# Block Designs: bd/MB/MB.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB || ORIG_REF_NAME==MB} -quiet] -quiet

# IP: bd/MB/ip/MB_uart_0_0/MB_uart_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_uart_0_0 || ORIG_REF_NAME==MB_uart_0_0} -quiet] -quiet

# IP: bd/MB/ip/MB_clk_wiz_1/MB_clk_wiz_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_clk_wiz_1 || ORIG_REF_NAME==MB_clk_wiz_1} -quiet] -quiet

# IP: bd/MB/ip/MB_sha256_0_1/MB_sha256_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_sha256_0_1 || ORIG_REF_NAME==MB_sha256_0_1} -quiet] -quiet

# XDC: c:/Users/gavwa/Desktop/Workin_Dir/Hardware_improve/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/MB_ooc.xdc
