# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MB/ip/MB_rst_clk_wiz_0_50M_0/MB_rst_clk_wiz_0_50M_0.xci
# IP: The module: 'MB_rst_clk_wiz_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_rst_clk_wiz_0_50M_0/MB_rst_clk_wiz_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_rst_clk_wiz_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_rst_clk_wiz_0_50M_0/MB_rst_clk_wiz_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_rst_clk_wiz_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_rst_clk_wiz_0_50M_0/MB_rst_clk_wiz_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_rst_clk_wiz_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MB/ip/MB_rst_clk_wiz_0_50M_0/MB_rst_clk_wiz_0_50M_0.xci
# IP: The module: 'MB_rst_clk_wiz_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_rst_clk_wiz_0_50M_0/MB_rst_clk_wiz_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_rst_clk_wiz_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_rst_clk_wiz_0_50M_0/MB_rst_clk_wiz_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_rst_clk_wiz_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_rst_clk_wiz_0_50M_0/MB_rst_clk_wiz_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_rst_clk_wiz_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
