# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrs.xdc

# Block Designs: bd/MB/MB.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB || ORIG_REF_NAME==MB} -quiet] -quiet

# IP: bd/MB/ip/MB_mdm_1_5/MB_mdm_1_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_mdm_1_5 || ORIG_REF_NAME==MB_mdm_1_5} -quiet] -quiet

# IP: bd/MB/ip/MB_axi_bram_ctrl_0_3/MB_axi_bram_ctrl_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_axi_bram_ctrl_0_3 || ORIG_REF_NAME==MB_axi_bram_ctrl_0_3} -quiet] -quiet

# IP: bd/MB/ip/MB_axi_bram_ctrl_0_bram_2/MB_axi_bram_ctrl_0_bram_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_axi_bram_ctrl_0_bram_2 || ORIG_REF_NAME==MB_axi_bram_ctrl_0_bram_2} -quiet] -quiet

# IP: bd/MB/ip/MB_simple_axi_writer_0_0/MB_simple_axi_writer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_simple_axi_writer_0_0 || ORIG_REF_NAME==MB_simple_axi_writer_0_0} -quiet] -quiet

# IP: bd/MB/ip/MB_axi_gpio_0_0/MB_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_axi_gpio_0_0 || ORIG_REF_NAME==MB_axi_gpio_0_0} -quiet] -quiet

# IP: bd/MB/ip/MB_axi_uartlite_0_1/MB_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_axi_uartlite_0_1 || ORIG_REF_NAME==MB_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/MB/ip/MB_microblaze_0_6/MB_microblaze_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_microblaze_0_6 || ORIG_REF_NAME==MB_microblaze_0_6} -quiet] -quiet

# IP: bd/MB/ip/MB_dlmb_v10_8/MB_dlmb_v10_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_dlmb_v10_8 || ORIG_REF_NAME==MB_dlmb_v10_8} -quiet] -quiet

# IP: bd/MB/ip/MB_ilmb_v10_8/MB_ilmb_v10_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_ilmb_v10_8 || ORIG_REF_NAME==MB_ilmb_v10_8} -quiet] -quiet

# IP: bd/MB/ip/MB_dlmb_bram_if_cntlr_8/MB_dlmb_bram_if_cntlr_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_dlmb_bram_if_cntlr_8 || ORIG_REF_NAME==MB_dlmb_bram_if_cntlr_8} -quiet] -quiet

# IP: bd/MB/ip/MB_ilmb_bram_if_cntlr_8/MB_ilmb_bram_if_cntlr_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_ilmb_bram_if_cntlr_8 || ORIG_REF_NAME==MB_ilmb_bram_if_cntlr_8} -quiet] -quiet

# IP: bd/MB/ip/MB_lmb_bram_8/MB_lmb_bram_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_lmb_bram_8 || ORIG_REF_NAME==MB_lmb_bram_8} -quiet] -quiet

# IP: bd/MB/ip/MB_clk_wiz_0_2/MB_clk_wiz_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_clk_wiz_0_2 || ORIG_REF_NAME==MB_clk_wiz_0_2} -quiet] -quiet

# IP: bd/MB/ip/MB_rst_clk_wiz_0_50M_0/MB_rst_clk_wiz_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_rst_clk_wiz_0_50M_0 || ORIG_REF_NAME==MB_rst_clk_wiz_0_50M_0} -quiet] -quiet

# IP: bd/MB/ip/MB_axi_smc_4/MB_axi_smc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_axi_smc_4 || ORIG_REF_NAME==MB_axi_smc_4} -quiet] -quiet

# XDC: c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/MB_ooc.xdc
